name: Post Slack message

on:
  workflow_call:
    inputs:
      slack_channel_id:
        type: string
        required: true
        description: 'Slack Channel ID'
    secrets:
      slack_bot_token:
        required: false
jobs:
  send_slack_message:
    runs-on: [cpu]
    steps:
    - name: Post to a Slack channel
      id: slack
      #uses: slackapi/slack-github-action@v1.25.0
      uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ inputs.slack_channel_id }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
